clc;
clear all;
close all;
t=0:0.01:1;
f1=3;
x1=sin(2*pi*f1*t);
figure;
subplot(2,1,1);
plot(t,x1);
title('sine wave','Lalit Narayan');
xlabel('time--->');
ylabel('amplitude--->');
grid;
[rxx lag1]=xcorr(x1);
subplot(2,1,2);
plot(lag1,rxx);
grid;
title('auto-correlation function of sine wave','Lalit Narayan');
figure;
subplot(2,2,1);
plot(t,x1);
title('sine wave x1','Lalit Narayan');
xlabel('time--->');
ylabel('amplitude--->');
grid;
f2=2;
x2=sin(2*pi*f2*t);
subplot(2,2,2);
plot(t,x2);
title('sine wave x2','Lalit Narayan');
xlabel('time--->');,ylabel('amplitude--->');
grid;
[cxx lag2]=xcorr(x1,x2);
subplot(2,2,[3,4]);
plot(lag2,cxx);
grid;
title('cross-correlation function of sine wave','Lalit Narayan');